# Generated by Django 2.2.1 on 2019-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
